version: '3.2'

services:
  app:
    build:
      context: .
    container_name: application
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: 'library/postgres:latest'
    container_name: database
    environment:
      - POSTGRES_DB=mentoring
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password